name: Clear Cache

on:
  workflow_dispatch:
jobs:
  clear:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:
    - uses: MyAlbum/purge-cache@v1
      with:
        max-age: 604800 # Cache max 7 days since last use (this is the default)