name: pull latest llvm project and create PR if updated

on:
  workflow_dispatch:

jobs:
  pull:
    name: pull latest llvm project and create PR if updated
    runs-on: ubuntu-latest
    steps:
      - name: checkout Template Code in a separate folder
        uses: actions/checkout@v2
        with:
          path: 'mlir-standalone-template'
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          load-mode: strict
          path: 'mlir-standalone-template/'
      - name: Get LLVM
        uses: actions/checkout@v2
        with:
          repository: 'llvm/llvm-project'
          path: 'llvm-project'
      - name: Set environment variable llvm commit hash in llvm-project/mlir/examples/standalone/
        run: |
          echo "LLVM_COMMIT_HASH=$(cd llvm-project && git log --pretty=tformat:"%H" -n1 ./mlir/examples/standalone/)" >> $GITHUB_ENV
      - name: Get template code commit hash by using .github/workflows/get_commit_hash_from_yml.py
        run: |
          cd $GITHUB_WORKSPACE/mlir-standalone-template
          echo "TEMPLATE_COMMIT_HASH=$(python ./.github/workflows/get_commit_hash_from_yml.py)" >> $GITHUB_ENV
      - name: Update if the two strings TEMPLATE_COMMIT_HASH and LLVM_COMMIT_HASH are different. push to the TEMPLATE_COMMIT_HASH branch. create pull request
        if: env.TEMPLATE_COMMIT_HASH != env.LLVM_COMMIT_HASH
        run: |
          cd $GITHUB_WORKSPACE/mlir-standalone-template
          cp -r $GITHUB_WORKSPACE/llvm-project/mlir/examples/standalone/* .
          python .github/workflows/replace_commit_hash_in_yml.py ${{ env.LLVM_COMMIT_HASH }}
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git checkout -b "gh_latest_llvm"
          git add .
          git commit -m "Update to LLVM commit ${{ env.LLVM_COMMIT_HASH }}"
          git push origin "gh_latest_llvm"
          gh pr create --title "Update to LLVM commit ${{ env.LLVM_COMMIT_HASH }}" --body "Update to LLVM commit ${{ env.LLVM_COMMIT_HASH }}" --base main --head "gh_latest_llvm"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}